wandb_config:
project: '4_clients_2_fail_every_2_rounds'
entity: 'aiotwin-wandb'
run_name: 'example_run'
enabled: False
local_logging_config:
log_file_path: 'logs/example/example.log'
scalar_freq: 100