device: 'cpu'

client_id: '1'
client_type: 'TorchClient'
server_address: '192.168.18.11:5000'

trainer_config:
train_config:
train_dataset_id: 'cifar10/train'
epochs: 2
train_loader_params:
  batch_size: 16
  num_workers: 0
  shuffle: True
  pin_memory: True
optimizer:
  type: 'adam'
  params:
    lr: 0.001
#    momentum: 0.9
#    weight_decay: 0.0001
criterion:
  type: 'CrossEntropyLoss'
  params:
    reduction: 'mean'

validation_config:
main_metric: 'Accuracy'
eval_metrics: [ 'Accuracy' ]
eval_dataset_id: 'cifar10/val'
eval_loader_params:
  batch_size: 16
  num_workers: 0
  shuffle: False
  pin_memory: True


#config: [ 'logging_config.yaml',
#          'model_config.yaml',
#          'datasets_config.yaml' ]