device: 'cpu'
strategy_config:
strategy_type: 'FedAvg'
strategy_params:
  accept_failures: True
rounds: 10
local_rounds: 1
central_test_config:
central_eval_metrics: [ 'Accuracy' ]
central_main_metric: 'Accuracy'
central_log_freq: 100
central_dataset_id: 'cifar10/test'
central_loader_params:
  batch_size: 128
  num_workers: 0
  shuffle: False
  pin_memory: True

# logging config, model_config
config: ['../example_shared/logging_config.yaml',
         '../example_shared/model_config.yaml',
         '../example_shared/datasets_config.yaml']