base_address: '127.0.0.1'
port_range: '5050:5052'
topology:
  root:
    base_config: &aggregator_config 'config/example_hierarchical/aggregator_config.yaml'
    children:
      aggregators:
          [ { base_config: *aggregator_config,
                      children: {
                        num_clients: 5,
                        failure_rate: [],
                        base_config: &client_config 'config/example_hierarchical/client_config.yaml'
                      }
                  },

                    { base_config: *aggregator_config,
                      children: {
                        num_clients: 5,
                        failure_rate: [],
                        base_config: *client_config
                      }
                    },
        ]

config: [ '../example_shared/datasets_config.yaml',
          '../example_shared/logging_config.yaml' ]
